#!/usr/bin/env python3

import argparse
import os
import sys


parser = argparse.ArgumentParser(
    prog="ls_w_ext",
    description=(
        "write all filepaths ending in provided extension(s) in dir and all "
        "subdirs to stdout"
    )
)

parser.add_argument(
    "dir",
    default=".",
    help="dir to source files from",
    required=False,
)

parser.add_argument(
    "exts",
    help="file extension(s) for paths to list",
    nargs="+",
)

args = parser.parse_args()

if not os.path.isdir(args.dir):
    sys.exit(f"Target dir {args.dir} not found or is not a dir")

for ext in exts:
    if len(ext) == 0 or ext[0] != ".":
        sys.exit(f"Extension {ext} has length 0 or does not begin with '.'")


def _listdir_paths(target_dir: str):
    for filename in os.listdir(target_dir):
        yield os.path.join(target_dir, filename)


def _any_ext_match(filepath: str) -> bool:
    _, ext = os.path.splitext(filepath)

    return any([ext == arg_ext for arg_ext in args.exts])


def ls_w_ext(target_dir: str) -> None:
    for filepath in _listdir_paths(target_dir):
        if os.path.isdir(filepath):
            ls_w_ext(filepath)
        elif _any_ext_match(filepath):
            print(filepath)


ls_w_ext(args.dir)

